language: python
python:
  - "3.7"
dist: xenial   # required for Python >= 3.7

branches:
  only:
    - master

install:
  - pip install poetry

script:
  - poetry build
  - poetry config repositories.testpypi https://test.pypi.org/simple
  - poetry publish -r testpypi -u $TESTPYPI_USER -p $TESTPYPI_PASS -n

  - pip install auri --no-cache-dir --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple
  - auri device list
  - echo "Nice, no errors in dev - on to production you noble piece of software!"

  - poetry publish -u $PYPI_USER -p $PYPI_PASS -n
